In [13]:
from __future__ import print_function
import tensorflow as tf
import numpy as np
import pandas as pd
import keras
import matplotlib.pyplot as plt

from keras.layers import Dense
from keras.models import Sequential


In [15]:
# create a graph
graph = tf.Graph()

In [22]:
# establish the graph as the "deafult" graph
with graph.as_default():
    x = tf.constant(8, name = 'x-constant')
    y = tf.constant(9, name = 'y-constant')
    sum = tf.add(x, y, name='xy-sum')
    
    # Create a session
    # session will run the default graph
    with tf.Session() as sess:
        print(sum.eval())

17


In [24]:
# Vector Addition
primes = tf.constant([2,3,5,7,11,13], dtype=tf.int32)
print("primes:", primes)

ones = tf.ones([6], dtype=tf.int32)
print("ones:", ones)

beyond_primes = tf.add(primes,ones)
print("beyond_primes:", beyond_primes)

twos = tf.constant([2,2,2,2,2,2], dtype=tf.int32)
prime_doubled = primes*twos
print("prime_doubled:", prime_doubled)

primes: Tensor("Const_12:0", shape=(6,), dtype=int32)
ones: Tensor("ones_1:0", shape=(6,), dtype=int32)
beyond_primes: Tensor("Add_1:0", shape=(6,), dtype=int32)
prime_doubled: Tensor("mul:0", shape=(6,), dtype=int32)


In [28]:
# Tensor shapes

# A scalar (0-D tensor).
scalar = tf.zeros([])

# A vector with 3 elements.
vector = tf.zeros([3])

# A matrix with 2 rows and 3 columns.
matrix = tf.zeros([2, 3])

print('scalar has shape', scalar.get_shape())
print('vector has shape', vector.get_shape())
print('matrix has shape', matrix.get_shape())

scalar has shape ()
vector has shape (3,)
matrix has shape (2, 3)


In [31]:
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [36]:
primes = tf.constant([2, 3, 5, 7, 11, 13], dtype=tf.int32)
result = tf.multiply(primes,primes) - 1

with tf.Session() as sess:
    result = sess.run(result)
    print(result)

[  3   8  24  48 120 168]


In [40]:
matrix = tf.constant([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16]],
    dtype=tf.int32)
matrix.shape
tf.reshape(matrix,[8,-1])

<tf.Tensor 'Reshape:0' shape=(8, 2) dtype=int32>