In [69]:
import numpy as np
import keras
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [70]:
graph1 = tf.Graph()

In [71]:
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')

In [72]:
session = tf.Session(graph=graph1)
result = session.run(a)
print(result)
session.close()

[2]


In [73]:
with graph1.as_default():
    c = tf.add(a,b)

In [74]:
session = tf.Session(graph=graph1)

In [77]:
result = session.run(c)
print(result)
session.close()

[5]


In [85]:
with tf.Session(graph=graph1) as session:
    result = session.run(c)
    print(result)

[5]


In [90]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,3])
    Matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
    Tensor = tf.constant ([[[1,2,3],[4,5,6],[7,8,9]],[[4,5,6],[7,8,9],[1,5,8]]])

In [92]:
with tf.Session(graph=graph2) as sess:
    result = sess.run(Scalar)
    print("Scalar is ", result)
    result = sess.run(Vector)
    print("Vector is ", result)
    result = sess.run(Matrix)
    print ("Matrix is ", result)
    result = sess.run(Tensor)
    print ("Tensor is ", result)

Scalar is  2
Vector is  [5 6 3]
Matrix is  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor is  [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[4 5 6]
  [7 8 9]
  [1 5 8]]]


In [95]:
Scalar.shape
Tensor.shape

TensorShape([Dimension(2), Dimension(3), Dimension(3)])

In [99]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[4,5,6]])
    Matrix_two = tf.constant([[6,7,8], [2,4,6]])
    
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two

with tf.Session(graph=graph3) as sess:
    result1 = sess.run(add_1_operation)
    result2 = sess.run(add_2_operation)
    
    print ("result 1 is {}  and result is {}".format(result1, result2))

result 1 is [[ 7  9 11]
 [ 6  9 12]]  and result is [[ 7  9 11]
 [ 6  9 12]]


In [101]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[3,4,5], [1,2,3]])
    Matrix_two = tf.constant([[1,2,3], [7,8,9], [4,5,6]])
    
    result = tf.matmul(Matrix_one, Matrix_two)
    
with tf.Session(graph=graph4) as sess:
    result = sess.run(result)
    print(result)

[[51 63 75]
 [27 33 39]]


In [103]:
# define variables
v = tf.Variable(0)

# update values
update = tf.assign(v, v+1)

In [108]:
# initialize variables
init_op = tf.global_variables_initializer()

In [110]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(v))
    for i in range(3):
        sess.run(update)
        print(sess.run(v))

0
1
2
3


In [111]:
# placeholders in tf
a = tf.placeholder(tf.float32)

In [112]:
b = a * 2

In [115]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict={a:3.5})
    print(result)

7.0


In [116]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [119]:
# operations in tf
graph5 =tf.Graph()

with graph5.as_default():
    a = tf.constant([2])
    b = tf.constant([6])
    c = tf.add(a,b)
    d = tf.subtract(b,a)
    
with tf.Session(graph=graph5) as sess:
    result = sess.run(c)
    print(result)
    result = sess.run(d)
    print(result)


[8]
[4]
